- type: startingGear
  id: CluwneGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCluwne
    back: ClothingBackpackCluwne
    shoes: ClothingShoesCluwne
    mask: ClothingMaskCluwne
    id: CluwnePDA
    gloves: ClothingHandsGlovesCluwne
  storage:
    jumpsuit:
    - CluwneHorn

- type: startingGear
  id: HoloClownGear
  inhand:
  - BikeHorn

