- type: job
  id: ResearchAssistant
  name: job-name-research-assistant
  description: job-description-research-assistant
  playTimeTracker: JobResearchAssistant
  requirements:
    - !type:CharacterEmployerRequirement
      employers:
      - NanoTrasen
      - ZengHuPharmaceuticals
  startingGear: ResearchAssistantGear
  icon: "JobIconResearchAssistant"
  supervisors: job-supervisors-science
  access:
  - Research
  - Maintenance

- type: startingGear
  id: ResearchAssistantGear
  subGear:
  - ScientistPlasmamanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorWhite
    back: ClothingBackpackScience
    shoes: ClothingShoesColorWhite
    id: ResearchAssistantPDA
    ears: ClothingHeadsetScience
  storage:
    back:
    - BoxSurvival
    jumpsuit:
    - BookPsionicsGuidebook
    - BookScientistsGuidebook
