- type: antag
  id: SpaceNinja
  name: roles-antag-space-ninja-name
  antagonist: true
  setPreference: false
  objective: roles-antag-space-ninja-objective
  guides: [ SpaceNinja ]

#Ninja Gear
- type: startingGear
  id: SpaceNinjaGear
  subGear:
  - SpaceNinjaPlasmamanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitNinja
    back: ClothingBackpackSatchel
    mask: ClothingMaskNinja
    head: ClothingHeadHelmetSpaceNinja
    eyes: ClothingEyesVisorNinja
    gloves: ClothingHandsGlovesSpaceNinja
    outerClothing: ClothingOuterSuitSpaceNinja
    shoes: ClothingShoesSpaceNinja
    id: AgentIDCard
    ears: ClothingHeadsetGrey
    belt: EnergyKatana
    suitstorage: OxygenTankFilled
  inhand:
  - JetpackBlackFilled
  storage:
    back: # belt holds katana so satchel has the tools for sabotaging things
    - BoxSurvival
    - DrinkSakeBottleFull
    - FoodSnackDango
    - FoodSnackDango
    jumpsuit:
    - SpiderCharge
    - PinpointerStation

- type: startingGear
  id: SpaceNinjaPlasmamanGear
  parent: BasePlasmamanGear
  equipment:
    jumpsuit: ClothingUniformEnvirosuitColorBlack # TODO: actual ninja envirosuit
    suitstorage: PlasmaTankFilled
