- type: startingGear
  id: PirateGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitPirate
    back: ClothingBackpackSatchelLeather
    head: ClothingHeadBandBlack
    shoes: ClothingShoesBootsLaceup
    id: PiratePDA
    belt: ClothingBeltUtility
  storage:
    jumpsuit:
    - AppraisalTool

- type: startingGear
  id: PirateCaptainGear
  parent: PirateGear
  equipment:
    head: ClothingHeadHatPirate
    outerClothing: ClothingOuterCoatPirate
  storage:
    jumpsuit:
    - AppraisalTool
    - EnergyCutlass

- type: startingGear
  id: PirateFirstmateGear
  parent: PirateGear
  equipment:
    head: ClothingHeadHatPirateTricorn
    outerClothing: ClothingOuterCoatGentle
