#Misc outfit startingGear definitions.

# Laika sec glasses

- type: startingGear
  id: MobSecDogLaikaGear
  equipment:
    eyes: ClothingEyesGlassesSunglasses

#Oldstation Roles

- type: startingGear
  id: OldstationMedic
  equipment:
    jumpsuit: ClothingUniformJumpsuitMedicalDoctor
    neck: ClothingNeckStethoscope
    shoes: ClothingShoesColorWhite
    id: MedicalIDCard
    belt: ClothingBeltMedical
  storage:
    jumpsuit:
    - Brutepack
    - GlowstickBase


- type: startingGear
  id: OldstationGuard
  equipment:
    jumpsuit: ClothingUniformJumpsuitSec
    shoes: ClothingShoesBootsJack
    id: SecurityIDCard
  storage:
    jumpsuit:
    - Flash
    - GlowstickBase

- type: startingGear
  id: OldstationEngi
  equipment:
    jumpsuit: ClothingUniformJumpsuitEngineering
    shoes: ClothingShoesBootsWork
    id: EngineeringIDCard
    mask: ClothingMaskBreath
    gloves: ClothingHandsGlovesColorYellowBudget
    belt: ClothingBeltUtility
  storage:
    jumpsuit:
    - EmergencyOxygenTankFilled
    - GlowstickBase

- type: startingGear
  id: OldstationScientist
  equipment:
    jumpsuit: ClothingUniformJumpsuitScientist
    shoes: ClothingShoesColorWhite
    id: ResearchIDCard
  storage:
    jumpsuit:
    - Pen
    - GlowstickBase

#Syndicate Pirate Radio Listener

- type: startingGear
  id: SyndicateListenerGear
  subGear:
  - SyndicatePlasmamanGear # TODO: syndicate listener enviropyjamas
  equipment:
    jumpsuit: ClothingUniformJumpsuitPyjamaSyndicateBlack
    head: ClothingHeadPyjamaSyndicateBlack
    ears: ClothingHeadsetAltSyndicateListening
    gloves: ClothingHandsGlovesCombat
    shoes: ClothingShoesSlippers
    id: SyndiListeningPostPDA
  storage:
    jumpsuit:
    - BaseUplinkRadio20TC

# Mobsters

- type: startingGear
  id: MobsterGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitSuitBlackMob
    back: ClothingBackpack
    head: ClothingHeadHatFedoraBlack
    shoes: ClothingShoesBootsLaceup
    neck: ClothingNeckTieBlack
    outerClothing: ClothingOuterArmorBasicSlim
    id: PassengerPDA
    belt: ClothingBeltHolster
  inhand:
    - BaseBallBat
  storage:
    back:
    - DrinkWhiskeyBottleFullMobster # WD EDIT: BoxSurvival -> DrinkWhiskeyBottleFullMobster
    - WeaponSubMachineGunTypewriter
    - WeaponPistolViperWood
    - MagazinePistol

- type: startingGear
  id: MobsterGearAlt
  equipment:
    jumpsuit: ClothingUniformJumpsuitSuitBrown
    back: ClothingBackpack
    head: ClothingHeadHatFlatBrown
    shoes: ClothingShoesLeather
    neck: ClothingNeckTieBrown
    outerClothing: ClothingOuterArmorBasicSlim
    id: PassengerPDA
    belt: ClothingBeltSuspendersBlack
  inhand:
  - BaseBallBat
  storage:
    back:
    - DrinkWhiskeyBottleFullMobster # WD EDIT: BoxSurvival -> DrinkWhiskeyBottleFullMobster
    - WeaponSubMachineGunTypewriter
    - WeaponPistolViperWood
    - MagazinePistol
    jumpsuit:
    - CombatKnife
